# Generated by Django 6.0.5 on 2026-07-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('position', models.IntegerField()),
                ('inscrit_le', models.DateTimeField(auto_now_add=True)),
                ('a_des_privileges', models.BooleanField(default=False)),
            ],
        ),
    ]
